Changed Database access
the-codeboy/mensabot pull request #43
Opened 2022-10-05 20:52 UTC by NilEis

Removed the code that automatically connects to the database at startup and added connection and disconnection code.

2022-10-05 20:53 UTC, NilEis commented on .gitignore
> +target/classes/emojis.csv
I dont think this should be commited

2022-10-06 13:29 UTC, the-codeboy requested changes
I don't think emojis.csv should be in .gitignore

2022-10-06 15:28 UTC, the-codeboy commented
But it is in the repo https://github.com/the-codeboy/mensabot/blob/main/src/main/resources/emojis.csv

2022-10-06 15:49 UTC, NilEis commented
I removed emojis.csv from the gitignore file 👍

2022-10-06 23:01 UTC, NilEis commented
And I have reverted the changes because the file was in fact not needed

2022-10-06 23:03 UTC, NilEis commented
And I added the target folder to the gitignore

2022-10-07 20:43 UTC, the-codeboy approved these changes

2022-10-07 21:53 UTC, merged