Added ElMomentoDelMogus command
the-codeboy/mensabot pull request #51
Opened 2022-11-08 16:43 UTC by NilEis

2022-11-08 17:16 UTC, the-codeboy requested changes
I just need a few changes and I will merge it

2022-11-08 17:16 UTC, the-codeboy commented on src/main/java/ml/codeboy/thebot/CommandHandler.java
> +        registerCommand(new ElMomentoCommand());
```suggestion
```

2022-11-08 17:16 UTC, the-codeboy commented on src/main/java/ml/codeboy/thebot/commands/ElMomentoCommand.java
> +}
```suggestion
```

2022-11-14 10:48 UTC, the-codeboy commented
If you don't respond I will close this PR as inactive

2022-11-14 13:52 UTC, NilEis commented
I do not believe that your request is feasible.

2022-11-14 13:59 UTC, the-codeboy commented
In that case you may make a better suggestion if it suits you dear sir

2022-11-15 11:52 UTC, the-codeboy approved these changes
Looks good

2022-11-15 11:52 UTC, the-codeboy commented on src/main/java/ml/codeboy/thebot/commands/ElMomentoCommand.java
> +public class ElMomentoCommand extends Command {
```suggestion
public class ElMomentoCommand extends DebugCommand {
```

2022-11-15 11:53 UTC, merged